# Generated by Django 2.2.7 on 2019-11-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('buy', models.IntegerField()),
                ('sell', models.IntegerField()),
                ('diff', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'unique_together': {('datetime', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Foreign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('buy', models.IntegerField()),
                ('sell', models.IntegerField()),
                ('diff', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'unique_together': {('datetime', 'number')},
            },
        ),
    ]
